apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::346572289462:user/aws-sam-developer
      username: aws-sam-developer
      groups:
        - system:system_admin
